### PR TITLE
Feature: Notify / wake feeder via UDP socket

### PR DESCRIPTION
**Pull request by mattconnolly**
This feature adds a class Rapns::Notifier which allows a web or other process to wake the Rapns daemon from sleep to send a notification immediately. This allows a much longer sleep time for lower polling / log activity.

Example notifier usage:

``` ruby
require 'rapns/notifier'
notifier = Rapns::Notifier.new(udp_host, udp_port)
notifier.notify # => wakes the daemon.
```

This is left as a separate require because it isn't used in the daemon, and can be used externally.

### CODE REVIEW

**Comment by ileitch** [comment]
Nice! I'll likely make some changes to the API and how this is configured, but I like the idea, so going to merge. Thanks :)

**Comment by ileitch** [comment]
FYI, some thoughts on API changes I may make:

Use Rapns.configure:

``` ruby
Rapns.configure do |config|
  config.wakeup.host = ...
  config.wakeup.port = ...
end
```

Then, perhaps:

``` ruby
Rapns.wakeup_daemon # or just wakeup
```

I'll probably remove all references to `udp` in the user-facing code, as it's an implementation detail.

**Comment by mattconnolly** [comment]
Great. `Rapns.wakeup` will be much nicer to use, my current line of code is:

``` ruby
Rapns::Notifier.new(Rapns.config.udp_wake_host, Rapns.config.udp_wake_port).notify rescue nil
```

I agree that UDP should be removed from the name. Good thinking. config could be more like:

``` ruby
Rapns.config.wake = { :host => '127.0.0.1', :port => 1234 }
```

Thank

**Comment by mattconnolly** [comment]
We may also need a connect address since the binding socket may want to bind on '0.0.0.0' but the notifier will need an explicit address to connect to.

A rails app may be running on a separate machine, for example. So rapns could easily bind to '0.0.0.0', but the rails instance would need to know the IP address.

How about:

``` ruby
Rapns.config.wakeup = { :bind => '0.0.0.0', :connect => '10.1.2.3', :port => 1234 }
```

?

**Pull request merged**
