### PR TITLE
"content-available"-flag added

### PR DESCRIPTION
**Pull request by trnc-ck**
hi,

because i needed the "content-available"-flag in the APS array, i added it. you can merge it if you're interested!
- clemens

### CODE REVIEW

**Comment by ileitch** [comment]
Could you please link me to the official Apple documentation for this? I'd like to understand it more before accepting any new code.

**Comment by trnc-ck** [comment]
there you go:

http://developer.apple.com/library/ios/technotes/tn2280/_index.html#//apple_ref/doc/uid/DTS40011215-CH1-DELIVERING_YOUR_CONTENT-HOW_IS_THE_PUSH_NOTIFICATION_THAT_INITIATES_THE_NEWSSTAND_BACKGROUND_DOWNLOAD_DIFFERENT_FROM_OTHER_PUSH_NOTIFICATIONS___WILL_I_HAVE_TO_CHANGE_OR_MODIFY_MY_BACKEND_INFRASTRUCTURE_

**Comment by ileitch** [comment]
Thank you. I will implement this feature for 3.0, which I am currently working on (Google Cloud Messaging support, Android). I have a different approach in mind than a new column.

**Comment by trnc-ck** [comment]
any news on this?

**Comment by ileitch** [comment]
I haven't forgotten about this, I just haven't had much time to work on rapns recently.

The reason I haven't accepted this PR as-is is because there have been a couple of occasions thus far where new minor features required a new column. I'd rather not add a new column each time (it's annoying for people upgrading). I instead want to add a single internal column for things like this.

I plan to implement this for 3.0, which includes a large migration, so it makes sense to add it then.

**Pull request closed without merging**
