### PR TITLE
Payload size fix: the 256 bytes limitation is on payload but not the entire packet

### PR DESCRIPTION
**Pull request by forresty**
See

http://developer.apple.com/library/ios/#documentation/NetworkingInternet/Conceptual/RemoteNotificationsPG/CommunicatingWIthAPS/CommunicatingWIthAPS.html#//apple_ref/doc/uid/TP40008194-CH101-SW4

This would break support for Ruby 1.8.6 though, since String.bytesize is added in Ruby 1.8.7

And also there are utf8 mulit-byte issues which I will try to identify and fix, in that case life will be much easier if we stick to using String.bytesize

Can we just drop support for Ruby versions earlier than 1.8.7?

### CODE REVIEW

**Comment by ileitch** [comment]
In 9cae5cf you removed the suggestion to condense the device attributes. Why is this? They're still part of the payload.

**Comment by forresty** [comment]
My mistake. I should not have changed it... Must be in a terrible mind-state

Have you checked 58b42d2ed618a69dcde4056ec14d045989fb3b42 and 4bba7b8fbb7467d9c86ec5cf47bde72b8bec5c38?

Maybe you want to just cherry-pick them?

**Comment by ileitch** [comment]
Cherry-picked, thanks.

**Comment by forresty** [comment]
Just realized I obviously typed "utf8" when I meant "utc" in one of the commit messages, no doubt I was in a terrible mind state, so shame :(

Thanks for the acceptance by the way. I really like this library, you rock!

**Pull request closed without merging**
