### PR TITLE
Support for MDM messages

### PR DESCRIPTION
**Pull request by dei79**
Apple supports a new notification message payload for MobileDeviceManagement solutions. As specified no other key is allowed in the hash when sending mdm messaged. This pull requests extends rapns for support of mdm messages!

### CODE REVIEW

**Comment by ileitch** [comment]
I have added MDM support in a607392 which does not require a migration. Can you please give it a try?

I will be adding support for multiple certs/apps in the near future.

**Comment by dei79** [comment]
Hi Ian,

I will try. So check my fork, I added multiple certs and database
driven certs. If you like it I can pull or we discuss the solution.

Cheers
Dirk

Sent from my iPad

On 09.06.2012, at 22:54, Ian Leitch
reply@reply.github.com
wrote:

**Comment by ileitch** [comment]
This is all now implemented in master. Please give it a try.

**Comment by zmajstor** [comment]
Great work with MDM addition. Just one small problem: I've tried recent version (2.0.1) in production environment and it seems that APNS did received MDM payload without any error, but shortly after that feedback_receiver.rb reported error - but without Device token (?) and with validation error trying to save a record in table 'rapns_feedback' - any idea what went wrong?

Log:
$ bundle exec rapns production -f
[2012-07-24 23:32:31] [DeliveryHandler:my_app2] Connected to gateway.push.apple.com:2195
[2012-07-24 23:32:31] [FeedbackReceiver:my_app2] Connected to feedback.push.apple.com:2196
[2012-07-24 23:33:32] [FeedbackReceiver:my_app2] Connected to feedback.push.apple.com:2196
[2012-07-24 23:33:46] [DeliveryHandler:my_app2] 3 sent to 92e5bf612965f22a72a5b17b9516fc689e5b98b2fe4d3d5f8d8d333398b82430
[2012-07-24 23:34:33] [FeedbackReceiver:my_app2] Connected to feedback.push.apple.com:2196
[2012-07-24 23:34:33] [FeedbackReceiver:my_app2] Delivery failed at 2012-07-24 21:33:46 UTC for 92e5bf612965f22a72a5b17b9516fc689e5b98b2fe4d3d5f8d8d333398b82430
[2012-07-24 23:34:33] [ERROR] ActiveRecord::RecordInvalid, Validation failed: Device token can't be blank, Device token is invalid, Failed at can't be blank
...

**Comment by dei79** [comment]
you need a device token also when you send MDM messages. Normally you should get a validation error when you store the message into the queue. didn't you?

**Comment by ileitch** [comment]
The error is coming from the feedback service. I've opened issue #52, please discuss there.

**Comment by zmajstor** [comment]
@dei79 I've stored message in the queue with device token and key as well:

``` ruby
n = Rapns::Notification.new 
n.app = "my_app"
n.device_token = "92e5bf61...."
n.mdm = "F9A811...."  
n.save!
```

let's discuss at issue #52

**Pull request closed without merging**
